# Generated by Django 3.1.1 on 2020-09-08 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200908_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('category', 'color', 'width', 'height')},
        ),
    ]
