# Generated by Django 3.1.1 on 2020-09-09 15:47

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20200908_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('length', models.IntegerField(default=25)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.color')),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterField(
            model_name='height',
            name='value',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='width',
            name='value',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('name', 'number')},
            },
        ),
        migrations.CreateModel(
            name='TurfRoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('SEALED', 'Sealed'), ('OPENED', 'Opened'), ('DEPLETED', 'Depleted')], default='SEALED', max_length=63)),
                ('remain', models.IntegerField(default=25)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.rollspec')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rollspec',
            name='height',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.height'),
        ),
        migrations.AddField(
            model_name='rollspec',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.warehouse'),
        ),
        migrations.AddField(
            model_name='rollspec',
            name='width',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.width'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
        migrations.AddField(
            model_name='product',
            name='spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stock.rollspec'),
        ),
        migrations.AlterUniqueTogether(
            name='rollspec',
            unique_together={('category', 'color', 'height', 'width', 'length')},
        ),
    ]
