# Generated by Django 3.1.1 on 2020-09-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20200909_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
