# Generated by Django 3.1.1 on 2020-09-09 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20200909_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rollspec',
            name='location',
        ),
        migrations.AddField(
            model_name='turfroll',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stock.warehouse'),
        ),
    ]
