# Generated by Django 3.1.1 on 2020-09-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20200909_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turfroll',
            old_name='remain',
            new_name='available',
        ),
        migrations.AddField(
            model_name='turfroll',
            name='reserved',
            field=models.IntegerField(default=0),
        ),
    ]
