# Generated by Django 3.1.1 on 2020-09-13 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_turfroll_delivered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turfroll',
            old_name='delivered',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='turfroll',
            name='available',
        ),
        migrations.RemoveField(
            model_name='turfroll',
            name='reserved',
        ),
    ]
