# Generated by Django 3.1.1 on 2020-09-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_auto_20200913_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='turfroll',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
