# Generated by Django 3.1.1 on 2020-09-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_auto_20200920_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_stock',
            field=models.BooleanField(default=False),
        ),
    ]
