# Generated by Django 3.1.1 on 2020-09-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_auto_20200929_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='turfroll',
            name='original_size',
            field=models.IntegerField(default=0),
        ),
    ]
