# Generated by Django 3.1.1 on 2020-09-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_turfroll_original_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_stock',
        ),
    ]
