# Generated by Django 3.1.1 on 2020-10-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_auto_20201003_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='turfroll',
            name='note',
            field=models.TextField(blank=True, max_length=511, null=True),
        ),
    ]
