# Generated by Django 3.1.1 on 2020-10-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_turfroll_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='height',
            name='value',
            field=models.FloatField(default=30),
        ),
        migrations.AlterField(
            model_name='rollspec',
            name='length',
            field=models.FloatField(default=25),
        ),
        migrations.AlterField(
            model_name='width',
            name='value',
            field=models.FloatField(default=2),
        ),
    ]
