version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.6
                environment:
                    DATABASE_URL: postgres://conductor:@localhost:5432
                    DB_HOST: localhost
                    DB_NAME: turf_portal
                    DB_USER: postgres
                    DB_PASSWORD: postgres
        steps:
            - checkout
            - run:
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
            - run:
                name: Running tests
                command: |
                    . venv/bin/activate
                    python manage.py test

