version: 2
jobs:
    build:
        context: turf-portal-build
        docker:
            - image: circleci/python:3.6
        steps:
            - checkout
            - run:
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
            - run:
                name: Running tests
                command: |
                    . venv/bin/activate
                    python manage.py test

