# Generated by Django 3.1.1 on 2021-01-20 21:35

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=511)),
                ('method', models.CharField(choices=[('CARD', 'Card'), ('CASH', 'Cash'), ('EFT', 'EFT'), ('OTHER', 'Other')], default='CARD', max_length=255)),
                ('amount', models.FloatField(default=0.0)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
