# Generated by Django 3.1.1 on 2021-01-20 21:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_auto_20210120_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 21, 46, 50, 347331, tzinfo=utc)),
        ),
    ]
