# Generated by Django 3.1.1 on 2021-01-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_auto_20210120_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='Amount (R'),
        ),
    ]
