# Generated by Django 3.1.1 on 2020-09-15 14:45

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0011_auto_20200913_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PAYMENT_OUTSTANDING', 'Payment_Outstanding'), ('CLOSED', 'Closed')], default='DRAFT', max_length=255)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, max_length=1023, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sales.buyer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sales.order')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
