# Generated by Django 3.1.1 on 2020-09-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_remove_invoice_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PAYMENT OUTSTANDING', 'Payment Outstanding'), ('CLOSED', 'Closed')], default='DRAFT', max_length=255),
        ),
    ]
