# Generated by Django 3.1.1 on 2020-09-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('EFT', 'EFT'), ('CASH', 'Cash'), ('OTHER', 'Other')], default='EFT', max_length=255),
        ),
    ]
