# Generated by Django 3.1.1 on 2020-09-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='closed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
