# Generated by Django 3.1.1 on 2020-09-19 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_auto_20200919_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='closed_date',
        ),
    ]
