# Generated by Django 3.1.1 on 2020-09-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_remove_invoice_closed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='closed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
