# Generated by Django 3.1.1 on 2020-09-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_invoice_closed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
