# Generated by Django 3.1.1 on 2020-09-15 23:57

from django.db import migrations, models
from invoice.models import Invoice


def update_invoice_number(apps, schema_editor):
    """
    All invoice number should be in the format of: BUYER_NAME-INV-DATE
    """
    for invoice in Invoice.objects.all():
        if "-INV-" not in invoice.number:
            buyer_name = invoice.number.split("-")[0]
            date_str = invoice.number.split("-")[-1]
            new_number = f"{buyer_name}-INV-{date_str}"
            invoice.number = new_number
            invoice.save()

class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_auto_20200920_1049'),
    ]

    operations = [
        migrations.RunPython(update_invoice_number),
    ]
