# Generated by Django 3.1.1 on 2021-01-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_update_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PAYMENT OUTSTANDING', 'Payment Outstanding'), ('PAYMENT PENDING', 'Payment Pending'), ('CLOSED', 'Closed')], default='DRAFT', max_length=255),
        ),
    ]
