# Generated by Django 3.1.1 on 2020-09-08 11:33

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20200908_1049'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('price', models.FloatField(default=0.0)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sales.buyer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.product')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
