# Generated by Django 3.1.1 on 2020-09-08 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20200908_1407'),
        ('sales', '0002_buyerproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerproduct',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sales.buyer'),
        ),
        migrations.AlterField(
            model_name='buyerproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stock.product'),
        ),
    ]
