# Generated by Django 3.1.1 on 2020-09-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20200909_1627'),
        ('sales', '0003_auto_20200908_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyerproduct',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='buyerproduct',
            unique_together={('buyer', 'product')},
        ),
    ]
