# Generated by Django 3.1.1 on 2020-09-09 16:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20200909_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='R'),
        ),
    ]
