# Generated by Django 3.1.1 on 2020-09-09 16:34

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20200909_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))], verbose_name='Price (R/m)'),
        ),
    ]
