# Generated by Django 3.1.1 on 2020-09-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_order_orderline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
