# Generated by Django 3.1.1 on 2020-09-12 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20200912_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerproduct',
            name='price',
            field=models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(50.0)]),
        ),
    ]
