# Generated by Django 3.1.1 on 2020-09-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('INVOICED', 'Invoiced'), ('DELIVERED', 'DELIVERED'), ('CLOSED', 'Closed')], default='DRAFT', max_length=255),
        ),
    ]
