# Generated by Django 3.1.1 on 2020-09-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_order_closed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('INVOICED', 'Invoiced'), ('DELIVERED', 'Delivered'), ('CLOSED', 'Closed')], default='DRAFT', max_length=255),
        ),
    ]
