# Generated by Django 3.1.1 on 2020-09-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_auto_20200919_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
