# Generated by Django 3.1.1 on 2020-09-28 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_product_has_stock'),
        ('sales', '0016_auto_20200928_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='buyer_product',
        ),
        migrations.AddField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stock.product'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='total',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
