# Generated by Django 3.1.1 on 2020-10-05 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_auto_20201003_2238'),
        ('sales', '0017_auto_20200928_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='roll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stock.turfroll'),
        ),
    ]
